### ISSUE TITLE
any plans to add a circular slider to this? 

### ISSUE THREAD

**Issue by Fanna1119** [freddie-nelson/vue3-slider#1]
would be awesome to see a circular slider to this, no current ones exist in vue3 :D

**Comment by freddie-nelson** [comment]
Great Idea! never thought about this but I'll look into it and make sure to get back to you 👍

**Comment by freddie-nelson** [comment]
added in 1.4.0 😄

**Comment by Fanna1119** [comment]
> added in 1.4.0

WOW. Astonished by the time you managed to incorporate this :fire:
