### ISSUE TITLE
Uncaught TypeError when vue dev server refreshes with a change

### ISSUE THREAD

**Issue by jeffderek** [freddie-nelson/vue3-slider#12]
It's possible I'm out of my depth here and don't know what I'm doing, but every time I make a change to the component that has the slider in it, I get the following error

![image](https://user-images.githubusercontent.com/3788655/118851013-588eda80-b89f-11eb-9c89-490a7f5118e5.png)

I'm using vue 3.0.0 & vue3-slider 1.6.2.  

`    <Slider
        ref="slider"
        v-model="vol"
        :color="color"
        track-color="#c9c9c9"
        orientation="vertical"
        width="90%"
        :height="20"
        @change="handleChange"
    />`

**Comment by freddie-nelson** [comment]
fixed

**Comment by davidchieregato** [comment]
I have the same issue on the last 1.6.4 version..
<img width="325" alt="err" src="https://user-images.githubusercontent.com/33154465/127474171-a5bae5d4-6a5d-4d7a-be43-57e5ca315057.png">

**Comment by freddie-nelson** [comment]
@davidchieregato not sure why this error has creeped up again but it should be fixed in 1.6.5 :+1:
