### ISSUE TITLE
Support for multiple sliders ?

### ISSUE THREAD

**Issue by oliv3** [freddie-nelson/vue3-slider#14]
Hi, thanks for this component, it will probably fit my needs.

I'm trying to use multiple sliders, and it seems that when `@drag-end` is called when a slider changes, the callback is triggered in **all** the sliders ?

Thanks,

**Comment by freddie-nelson** [comment]
Hey oliv,

Thanks for pointing out this bug to me and choosing my component. It is currently 11pm where I am but tomorrow I will look into this issue for you.

Cheers, Freddie

**Comment by freddie-nelson** [comment]
fixed in vue3-slider@1.6.4 :+1:
