### ISSUE TITLE
Circular slider depends on window.scrollY

### ISSUE THREAD

**Issue by Suchyy** [freddie-nelson/vue3-slider#16]
Hi,
I have problem with slider in circular orientation. In my project I have circular slider in popup, small div with position: fixed above of the rest of the web page. When I am opening popup with window.scrollY = 0 then it is all good, but when window.scrollY is more than 0 then slider in circular orientation is unusable. Event dragging is working but value, track filling and circle position aren't changing.
It is like I am always hovering on bottom of the slider when scrollY isn't 0.

Workaround: save scroll position, scroll to position 0, show popup, close popup, scroll to saved position.
It works that way but it is not good solution for me.

**Comment by freddie-nelson** [comment]
Thanks for the bug report, this should be fixed in 1.6.8 :+1:
