### ISSUE TITLE
Non-linear steps

### ISSUE THREAD

**Issue by anders-f** [freddie-nelson/vue3-slider#19]
Hi!

Is it possible for the slider to use non-linear steps? For instance, to send in an array of values that the slider should use?

**Comment by freddie-nelson** [comment]
There isn't an option for something like this built directly into the slider but it can be implemented relatively easily. I've attached an example of how I would go about doing this, hopefully you find it helpful :)

[example](https://github.com/freddie-nelson/vue3-slider/files/8709660/example.txt)
