### ISSUE TITLE
circular slider repeater Boolean (enhancement)

### ISSUE THREAD

**Issue by Fanna1119** [freddie-nelson/vue3-slider#2]
Problem:
When mouse/touch dragging the circular slider to 100%(last value) then beyond, it would go back to 0 again starting a new cycle.

Suggestion:
A boolean to set `repeat: false` to stop at last value(100%) when trying to drag beyond 100%

```html

<v-slider width="300px" orientation="circular" repeat="false" />

```

**Comment by freddie-nelson** [comment]
added in 1.4.1
