### ISSUE TITLE
Add a knob

### ISSUE THREAD

**Issue by mst101** [freddie-nelson/vue3-slider#20]
HI Freddie, thanks for this. It appears to be one of the few open source Vue 3 sliders that actually work! 

Is there any chance you could add the option of displaying a knob to help users understand that a value can be changed (and how to do it). This would also increase the draggable area, making it easier to interact with the component.

**Comment by GRhonin** [comment]
HI Freddie,thanks too, actually i tried to added a knob, can i merge it to yours?

**Comment by freddie-nelson** [comment]
Just got off work but I'll be able to look at this tomorrow

**Comment by GRhonin** [comment]
Hi Freddie,I commit a pr,can you check it and merge it to main if it is no problem please,thank you

**Comment by freddie-nelson** [comment]
Similar feature alwaysShowHandle added in latest release.
