### ISSUE TITLE
Scroll isn't locked on y-axis (on mobile)

### ISSUE THREAD

**Issue by maximelebreton** [freddie-nelson/vue3-slider#27]
Hello @freddie-nelson, and thanks for your work on this slider!

When you're on mobile, and on a page that can scroll, if you start to slide, the page scrolls with the slide, and I think thats a unexcepted behaviour.

I try to pass the preventDefault() event, but it doesn't seem to be transmitted.

The ideal would be to have an option to **prevent scroll** on **x-axis**, **y-axis** and **both**,
like:  
**preventScroll**: `true`, `x`, `y`

Thanks!

**Comment by freddie-nelson** [comment]
Hi @maximelebreton, I'm not able to reproduce this behaviour. Any chance you could provide a codepen / fiddle with a reproducible example?
