### ISSUE TITLE
tooltip/tooltipText z-index can't be adjusted

### ISSUE THREAD

**Issue by martintomov** [freddie-nelson/vue3-slider#28]
if you try to create a multiple slider input component, both vertical and horizontal, the tooltip & tooltipText stays bellow the z-index of other sliders;

example:
<img width="591" alt="Screenshot 2023-11-26 at 15 26 06" src="https://github.com/freddie-nelson/vue3-slider/assets/101264514/688eff8f-79ec-4ecf-bab2-e65e05272aac">

**Comment by freddie-nelson** [comment]
added tooltipStyles prop in 1.10.0
