### ISSUE TITLE
flip circular slider vertically

### ISSUE THREAD

**Issue by plagerweij** [freddie-nelson/vue3-slider#3]
It would be nice if the circular slider had an option to be flipped vertically (rotate 180°). I'm not able to do this well using plain css tricks.

Something like this:
```vue
<vue3-slider orientation="circular" flip="true" />
```

**Comment by freddie-nelson** [comment]
Sorry for the late reply, I have been busy with other things however I will look into this tomorrow 👍

**Comment by freddie-nelson** [comment]
Out in 1.6.0, implemented as flip and circle offset props

**Comment by plagerweij** [comment]
Awesome. Works perfectly :thumbsup:
