### ISSUE TITLE
v-model not changing slider position

### ISSUE THREAD

**Issue by plagerweij** [freddie-nelson/vue3-slider#5]
There seems to be an issue with `v-model` data binding. When a method tries to change a slider value, the value gets correctly updated, but the slider does not move and just stays at its current position:

```vue
<template>
  <vue3-slider v-model="myNumber" />
  <h1 @click="changeNumber">{{ myNumber }}</h1>
</template>

<script lang="ts">
import { defineComponent } from "vue"
import slider from "vue3-slider"

export default defineComponent({
  name: "App",
  components: {
    "vue3-slider": slider
  },
  data() {
    return {
      myNumber: 50
    }
  },
  methods: {
    changeNumber() {
      this.myNumber = 42
    }
  }
})
</script>
```

So when the number is clicked, it changes to 42, but the slider does not reflect this change.

I'm using:
vue 3.0.7
vue3-slider 1.5.3

**Comment by freddie-nelson** [comment]
Good catch, I will make sure to fix this for the next release 👍

**Comment by freddie-nelson** [comment]
out in 1.5.4, if you find any edge cases in the latest release be sure to let me know 😄
